apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      containers:
      - name: homebridge
        image: homebridge/homebridge:2024-09-03
        ports:
        - containerPort: 8581
        volumeMounts:
        - name: homebridge-storage
          mountPath: /homebridge
        env:
        - name: TZ
          value: Asia/Tokyo
      volumes:
      - name: homebridge-storage
        persistentVolumeClaim:
          claimName: homebridge-pvc
