apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebridge-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/Users/yuki/kubernetes-volumes/homebridge"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage
