apiVersion: v1
kind: Service
metadata:
  name: homebridge
spec:
  type: NodePort
  ports:
    - port: 8581
      targetPort: 8581
      nodePort: 30031
      protocol: TCP
  selector:
    app: homebridge
